[2018-05-06 19:38:03,145] {models.py:167} INFO - Filling up the DagBag from /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py
[2018-05-06 19:38:06,240] {base_task_runner.py:112} INFO - Running: ['bash', '-c', 'airflow run PropertyClassification_test_pipeline branching 2018-05-06T19:22:58.482924 --job_id 97 --raw -sd /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py']
[2018-05-06 19:38:06,587] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:38:06,586] {__init__.py:57} INFO - Using executor SequentialExecutor
[2018-05-06 19:38:06,991] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:38:06,991] {models.py:167} INFO - Filling up the DagBag from /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py
[2018-05-06 19:38:09,992] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:38:09,992] {models.py:1126} INFO - Dependencies all met for <TaskInstance: PropertyClassification_test_pipeline.branching 2018-05-06 19:22:58.482924 [queued]>
[2018-05-06 19:38:09,998] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:38:09,998] {models.py:1126} INFO - Dependencies all met for <TaskInstance: PropertyClassification_test_pipeline.branching 2018-05-06 19:22:58.482924 [queued]>
[2018-05-06 19:38:09,998] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:38:09,998] {models.py:1318} INFO - 
[2018-05-06 19:38:09,998] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-06 19:38:09,998] {base_task_runner.py:95} INFO - Subtask: Starting attempt 1 of 2
[2018-05-06 19:38:09,998] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-06 19:38:09,998] {base_task_runner.py:95} INFO - Subtask: 
[2018-05-06 19:38:10,006] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:38:10,006] {models.py:1342} INFO - Executing <Task(BranchPythonOperator): branching> on 2018-05-06 19:22:58.482924
[2018-05-06 19:38:10,015] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:38:10,014] {python_operator.py:81} INFO - Done. Returned value was: <Task(BranchPythonOperator): create_aerial_cropped_images>
[2018-05-06 19:38:10,015] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:38:10,015] {models.py:1417} ERROR - Can't convert 'BranchPythonOperator' object to str implicitly
[2018-05-06 19:38:10,015] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-06 19:38:10,015] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/models.py", line 1374, in run
[2018-05-06 19:38:10,015] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-06 19:38:10,015] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 106, in execute
[2018-05-06 19:38:10,015] {base_task_runner.py:95} INFO - Subtask:     logging.info("Following branch " + branch)
[2018-05-06 19:38:10,015] {base_task_runner.py:95} INFO - Subtask: TypeError: Can't convert 'BranchPythonOperator' object to str implicitly
[2018-05-06 19:38:10,015] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:38:10,015] {models.py:1433} INFO - Marking task as UP_FOR_RETRY
[2018-05-06 19:38:10,022] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:38:10,021] {models.py:1462} ERROR - Can't convert 'BranchPythonOperator' object to str implicitly
[2018-05-06 19:38:10,022] {base_task_runner.py:95} INFO - Subtask: /Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/ti_deps/deps/base_ti_dep.py:94: PendingDeprecationWarning: generator '_get_dep_statuses' raised StopIteration
[2018-05-06 19:38:10,022] {base_task_runner.py:95} INFO - Subtask:   for dep_status in self._get_dep_statuses(ti, session, dep_context):
[2018-05-06 19:38:10,023] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-06 19:38:10,023] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/bin/airflow", line 28, in <module>
[2018-05-06 19:38:10,023] {base_task_runner.py:95} INFO - Subtask:     args.func(args)
[2018-05-06 19:38:10,023] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/bin/cli.py", line 422, in run
[2018-05-06 19:38:10,023] {base_task_runner.py:95} INFO - Subtask:     pool=args.pool,
[2018-05-06 19:38:10,023] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/utils/db.py", line 53, in wrapper
[2018-05-06 19:38:10,023] {base_task_runner.py:95} INFO - Subtask:     result = func(*args, **kwargs)
[2018-05-06 19:38:10,023] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/models.py", line 1374, in run
[2018-05-06 19:38:10,023] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-06 19:38:10,023] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 106, in execute
[2018-05-06 19:38:10,023] {base_task_runner.py:95} INFO - Subtask:     logging.info("Following branch " + branch)
[2018-05-06 19:38:10,023] {base_task_runner.py:95} INFO - Subtask: TypeError: Can't convert 'BranchPythonOperator' object to str implicitly
[2018-05-06 19:38:11,244] {jobs.py:2083} INFO - Task exited with return code 1
[2018-05-06 19:41:32,504] {models.py:167} INFO - Filling up the DagBag from /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py
[2018-05-06 19:41:35,607] {base_task_runner.py:112} INFO - Running: ['bash', '-c', 'airflow run PropertyClassification_test_pipeline branching 2018-05-06T19:22:58.482924 --job_id 105 --raw -sd /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py']
[2018-05-06 19:41:35,933] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:41:35,933] {__init__.py:57} INFO - Using executor SequentialExecutor
[2018-05-06 19:41:36,325] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:41:36,325] {models.py:167} INFO - Filling up the DagBag from /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py
[2018-05-06 19:41:39,381] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:41:39,381] {models.py:1126} INFO - Dependencies all met for <TaskInstance: PropertyClassification_test_pipeline.branching 2018-05-06 19:22:58.482924 [queued]>
[2018-05-06 19:41:39,387] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:41:39,387] {models.py:1126} INFO - Dependencies all met for <TaskInstance: PropertyClassification_test_pipeline.branching 2018-05-06 19:22:58.482924 [queued]>
[2018-05-06 19:41:39,387] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:41:39,387] {models.py:1318} INFO - 
[2018-05-06 19:41:39,387] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-06 19:41:39,387] {base_task_runner.py:95} INFO - Subtask: Starting attempt 2 of 2
[2018-05-06 19:41:39,387] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-06 19:41:39,387] {base_task_runner.py:95} INFO - Subtask: 
[2018-05-06 19:41:39,395] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:41:39,395] {models.py:1342} INFO - Executing <Task(BranchPythonOperator): branching> on 2018-05-06 19:22:58.482924
[2018-05-06 19:41:39,403] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:41:39,402] {models.py:1417} ERROR - 'BranchPythonOperator' object is not callable
[2018-05-06 19:41:39,403] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-06 19:41:39,403] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/models.py", line 1374, in run
[2018-05-06 19:41:39,403] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-06 19:41:39,403] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 105, in execute
[2018-05-06 19:41:39,403] {base_task_runner.py:95} INFO - Subtask:     branch = super(BranchPythonOperator, self).execute(context)
[2018-05-06 19:41:39,403] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-06 19:41:39,403] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-06 19:41:39,403] {base_task_runner.py:95} INFO - Subtask: TypeError: 'BranchPythonOperator' object is not callable
[2018-05-06 19:41:39,403] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:41:39,403] {models.py:1439} INFO - All retries failed; marking task as FAILED
[2018-05-06 19:41:39,410] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:41:39,410] {models.py:1462} ERROR - 'BranchPythonOperator' object is not callable
[2018-05-06 19:41:39,410] {base_task_runner.py:95} INFO - Subtask: /Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/ti_deps/deps/base_ti_dep.py:94: PendingDeprecationWarning: generator '_get_dep_statuses' raised StopIteration
[2018-05-06 19:41:39,410] {base_task_runner.py:95} INFO - Subtask:   for dep_status in self._get_dep_statuses(ti, session, dep_context):
[2018-05-06 19:41:39,411] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-06 19:41:39,411] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/bin/airflow", line 28, in <module>
[2018-05-06 19:41:39,411] {base_task_runner.py:95} INFO - Subtask:     args.func(args)
[2018-05-06 19:41:39,411] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/bin/cli.py", line 422, in run
[2018-05-06 19:41:39,411] {base_task_runner.py:95} INFO - Subtask:     pool=args.pool,
[2018-05-06 19:41:39,411] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/utils/db.py", line 53, in wrapper
[2018-05-06 19:41:39,411] {base_task_runner.py:95} INFO - Subtask:     result = func(*args, **kwargs)
[2018-05-06 19:41:39,411] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/models.py", line 1374, in run
[2018-05-06 19:41:39,411] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-06 19:41:39,412] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 105, in execute
[2018-05-06 19:41:39,412] {base_task_runner.py:95} INFO - Subtask:     branch = super(BranchPythonOperator, self).execute(context)
[2018-05-06 19:41:39,412] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-06 19:41:39,412] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-06 19:41:39,412] {base_task_runner.py:95} INFO - Subtask: TypeError: 'BranchPythonOperator' object is not callable
[2018-05-06 19:41:40,608] {jobs.py:2083} INFO - Task exited with return code 1
