[2018-05-06 19:42:23,992] {models.py:167} INFO - Filling up the DagBag from /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py
[2018-05-06 19:42:30,151] {base_task_runner.py:112} INFO - Running: ['bash', '-c', 'airflow run PropertyClassification_test_pipeline branching 2018-05-06T19:41:12.717185 --job_id 108 --raw -sd /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py']
[2018-05-06 19:42:30,474] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:42:30,474] {__init__.py:57} INFO - Using executor SequentialExecutor
[2018-05-06 19:42:30,865] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:42:30,864] {models.py:167} INFO - Filling up the DagBag from /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py
[2018-05-06 19:42:33,832] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:42:33,832] {models.py:1126} INFO - Dependencies all met for <TaskInstance: PropertyClassification_test_pipeline.branching 2018-05-06 19:41:12.717185 [queued]>
[2018-05-06 19:42:33,836] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:42:33,836] {models.py:1126} INFO - Dependencies all met for <TaskInstance: PropertyClassification_test_pipeline.branching 2018-05-06 19:41:12.717185 [queued]>
[2018-05-06 19:42:33,836] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:42:33,836] {models.py:1318} INFO - 
[2018-05-06 19:42:33,836] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-06 19:42:33,836] {base_task_runner.py:95} INFO - Subtask: Starting attempt 1 of 2
[2018-05-06 19:42:33,836] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-06 19:42:33,837] {base_task_runner.py:95} INFO - Subtask: 
[2018-05-06 19:42:33,846] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:42:33,846] {models.py:1342} INFO - Executing <Task(BranchPythonOperator): branching> on 2018-05-06 19:41:12.717185
[2018-05-06 19:42:33,857] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:42:33,856] {models.py:1417} ERROR - 'BranchPythonOperator' object is not callable
[2018-05-06 19:42:33,857] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-06 19:42:33,857] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/models.py", line 1374, in run
[2018-05-06 19:42:33,857] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-06 19:42:33,857] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 105, in execute
[2018-05-06 19:42:33,858] {base_task_runner.py:95} INFO - Subtask:     branch = super(BranchPythonOperator, self).execute(context)
[2018-05-06 19:42:33,858] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-06 19:42:33,858] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-06 19:42:33,858] {base_task_runner.py:95} INFO - Subtask: TypeError: 'BranchPythonOperator' object is not callable
[2018-05-06 19:42:33,858] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:42:33,857] {models.py:1433} INFO - Marking task as UP_FOR_RETRY
[2018-05-06 19:42:33,864] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:42:33,864] {models.py:1462} ERROR - 'BranchPythonOperator' object is not callable
[2018-05-06 19:42:33,864] {base_task_runner.py:95} INFO - Subtask: /Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/ti_deps/deps/base_ti_dep.py:94: PendingDeprecationWarning: generator '_get_dep_statuses' raised StopIteration
[2018-05-06 19:42:33,864] {base_task_runner.py:95} INFO - Subtask:   for dep_status in self._get_dep_statuses(ti, session, dep_context):
[2018-05-06 19:42:33,865] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-06 19:42:33,865] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/bin/airflow", line 28, in <module>
[2018-05-06 19:42:33,866] {base_task_runner.py:95} INFO - Subtask:     args.func(args)
[2018-05-06 19:42:33,866] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/bin/cli.py", line 422, in run
[2018-05-06 19:42:33,866] {base_task_runner.py:95} INFO - Subtask:     pool=args.pool,
[2018-05-06 19:42:33,866] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/utils/db.py", line 53, in wrapper
[2018-05-06 19:42:33,866] {base_task_runner.py:95} INFO - Subtask:     result = func(*args, **kwargs)
[2018-05-06 19:42:33,866] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/models.py", line 1374, in run
[2018-05-06 19:42:33,866] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-06 19:42:33,866] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 105, in execute
[2018-05-06 19:42:33,866] {base_task_runner.py:95} INFO - Subtask:     branch = super(BranchPythonOperator, self).execute(context)
[2018-05-06 19:42:33,866] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-06 19:42:33,866] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-06 19:42:33,866] {base_task_runner.py:95} INFO - Subtask: TypeError: 'BranchPythonOperator' object is not callable
[2018-05-06 19:42:35,160] {jobs.py:2083} INFO - Task exited with return code 1
[2018-05-06 19:44:48,876] {models.py:167} INFO - Filling up the DagBag from /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py
[2018-05-06 19:44:52,060] {base_task_runner.py:112} INFO - Running: ['bash', '-c', 'airflow run PropertyClassification_test_pipeline branching 2018-05-06T19:41:12.717185 --job_id 112 --raw -sd /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py']
[2018-05-06 19:44:52,425] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:44:52,424] {__init__.py:57} INFO - Using executor SequentialExecutor
[2018-05-06 19:44:52,861] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:44:52,860] {models.py:167} INFO - Filling up the DagBag from /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py
[2018-05-06 19:44:55,939] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:44:55,939] {models.py:1126} INFO - Dependencies all met for <TaskInstance: PropertyClassification_test_pipeline.branching 2018-05-06 19:41:12.717185 [queued]>
[2018-05-06 19:44:55,944] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:44:55,944] {models.py:1126} INFO - Dependencies all met for <TaskInstance: PropertyClassification_test_pipeline.branching 2018-05-06 19:41:12.717185 [queued]>
[2018-05-06 19:44:55,944] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:44:55,944] {models.py:1318} INFO - 
[2018-05-06 19:44:55,944] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-06 19:44:55,944] {base_task_runner.py:95} INFO - Subtask: Starting attempt 2 of 2
[2018-05-06 19:44:55,944] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-06 19:44:55,944] {base_task_runner.py:95} INFO - Subtask: 
[2018-05-06 19:44:55,953] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:44:55,953] {models.py:1342} INFO - Executing <Task(BranchPythonOperator): branching> on 2018-05-06 19:41:12.717185
[2018-05-06 19:44:55,962] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:44:55,962] {models.py:1417} ERROR - 'PythonOperator' object is not callable
[2018-05-06 19:44:56,000] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-06 19:44:56,014] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/models.py", line 1374, in run
[2018-05-06 19:44:56,017] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-06 19:44:56,017] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 105, in execute
[2018-05-06 19:44:56,017] {base_task_runner.py:95} INFO - Subtask:     branch = super(BranchPythonOperator, self).execute(context)
[2018-05-06 19:44:56,017] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-06 19:44:56,017] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-06 19:44:56,017] {base_task_runner.py:95} INFO - Subtask: TypeError: 'PythonOperator' object is not callable
[2018-05-06 19:44:56,017] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:44:55,963] {models.py:1439} INFO - All retries failed; marking task as FAILED
[2018-05-06 19:44:56,021] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:44:56,020] {models.py:1462} ERROR - 'PythonOperator' object is not callable
[2018-05-06 19:44:56,021] {base_task_runner.py:95} INFO - Subtask: /Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/ti_deps/deps/base_ti_dep.py:94: PendingDeprecationWarning: generator '_get_dep_statuses' raised StopIteration
[2018-05-06 19:44:56,021] {base_task_runner.py:95} INFO - Subtask:   for dep_status in self._get_dep_statuses(ti, session, dep_context):
[2018-05-06 19:44:56,022] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-06 19:44:56,022] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/bin/airflow", line 28, in <module>
[2018-05-06 19:44:56,022] {base_task_runner.py:95} INFO - Subtask:     args.func(args)
[2018-05-06 19:44:56,022] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/bin/cli.py", line 422, in run
[2018-05-06 19:44:56,022] {base_task_runner.py:95} INFO - Subtask:     pool=args.pool,
[2018-05-06 19:44:56,022] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/utils/db.py", line 53, in wrapper
[2018-05-06 19:44:56,022] {base_task_runner.py:95} INFO - Subtask:     result = func(*args, **kwargs)
[2018-05-06 19:44:56,023] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/models.py", line 1374, in run
[2018-05-06 19:44:56,023] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-06 19:44:56,023] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 105, in execute
[2018-05-06 19:44:56,023] {base_task_runner.py:95} INFO - Subtask:     branch = super(BranchPythonOperator, self).execute(context)
[2018-05-06 19:44:56,023] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-06 19:44:56,023] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-06 19:44:56,023] {base_task_runner.py:95} INFO - Subtask: TypeError: 'PythonOperator' object is not callable
[2018-05-06 19:44:57,068] {jobs.py:2083} INFO - Task exited with return code 1
