[2018-05-07 01:26:51,861] {models.py:167} INFO - Filling up the DagBag from /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py
[2018-05-07 01:26:55,382] {base_task_runner.py:112} INFO - Running: ['bash', '-c', 'airflow run PropertyClassification_test_pipeline test_on_new_images 2018-05-07T01:23:50.810307 --job_id 180 --raw -sd /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py']
[2018-05-07 01:26:55,752] {base_task_runner.py:95} INFO - Subtask: [2018-05-07 01:26:55,752] {__init__.py:57} INFO - Using executor SequentialExecutor
[2018-05-07 01:26:56,206] {base_task_runner.py:95} INFO - Subtask: [2018-05-07 01:26:56,206] {models.py:167} INFO - Filling up the DagBag from /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py
[2018-05-07 01:26:59,427] {base_task_runner.py:95} INFO - Subtask: [2018-05-07 01:26:59,427] {models.py:1126} INFO - Dependencies all met for <TaskInstance: PropertyClassification_test_pipeline.test_on_new_images 2018-05-07 01:23:50.810307 [queued]>
[2018-05-07 01:26:59,432] {base_task_runner.py:95} INFO - Subtask: [2018-05-07 01:26:59,432] {models.py:1126} INFO - Dependencies all met for <TaskInstance: PropertyClassification_test_pipeline.test_on_new_images 2018-05-07 01:23:50.810307 [queued]>
[2018-05-07 01:26:59,433] {base_task_runner.py:95} INFO - Subtask: [2018-05-07 01:26:59,432] {models.py:1318} INFO - 
[2018-05-07 01:26:59,433] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-07 01:26:59,433] {base_task_runner.py:95} INFO - Subtask: Starting attempt 1 of 2
[2018-05-07 01:26:59,433] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-07 01:26:59,433] {base_task_runner.py:95} INFO - Subtask: 
[2018-05-07 01:26:59,442] {base_task_runner.py:95} INFO - Subtask: [2018-05-07 01:26:59,442] {models.py:1342} INFO - Executing <Task(PythonOperator): test_on_new_images> on 2018-05-07 01:23:50.810307
[2018-05-07 01:26:59,463] {base_task_runner.py:95} INFO - Subtask: [2018-05-07 01:26:59,462] {test.py:103} INFO - INITIATING TEST ........
[2018-05-07 01:26:59,464] {base_task_runner.py:95} INFO - Subtask: [2018-05-07 01:26:59,463] {models.py:1417} ERROR - [Errno 2] No such file or directory: '/Users/sam/All-Program/App-DataSet/HouseClassification/checkpoints/sam_new/overlaid/resnet'
[2018-05-07 01:26:59,464] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-07 01:26:59,464] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/models.py", line 1374, in run
[2018-05-07 01:26:59,464] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-07 01:26:59,464] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-07 01:26:59,464] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-07 01:26:59,464] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/jobs/train_cv_test.py", line 194, in test_new
[2018-05-07 01:26:59,464] {base_task_runner.py:95} INFO - Subtask:     dump_stats=True)
[2018-05-07 01:26:59,465] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/src/conv_net/test.py", line 113, in run
[2018-05-07 01:26:59,465] {base_task_runner.py:95} INFO - Subtask:     checkpoint_paths = self.get_checkpoint_path(which_checkpoint)
[2018-05-07 01:26:59,465] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/src/conv_net/train.py", line 106, in get_checkpoint_path
[2018-05-07 01:26:59,465] {base_task_runner.py:95} INFO - Subtask:     checkpoints = [str(filename.split('.')[0]) for filename in os.listdir(self.ckpt_path)
[2018-05-07 01:26:59,465] {base_task_runner.py:95} INFO - Subtask: FileNotFoundError: [Errno 2] No such file or directory: '/Users/sam/All-Program/App-DataSet/HouseClassification/checkpoints/sam_new/overlaid/resnet'
[2018-05-07 01:26:59,465] {base_task_runner.py:95} INFO - Subtask: [2018-05-07 01:26:59,465] {models.py:1433} INFO - Marking task as UP_FOR_RETRY
[2018-05-07 01:26:59,475] {base_task_runner.py:95} INFO - Subtask: [2018-05-07 01:26:59,475] {models.py:1462} ERROR - [Errno 2] No such file or directory: '/Users/sam/All-Program/App-DataSet/HouseClassification/checkpoints/sam_new/overlaid/resnet'
[2018-05-07 01:26:59,475] {base_task_runner.py:95} INFO - Subtask: /Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/ti_deps/deps/base_ti_dep.py:94: PendingDeprecationWarning: generator '_get_dep_statuses' raised StopIteration
[2018-05-07 01:26:59,475] {base_task_runner.py:95} INFO - Subtask:   for dep_status in self._get_dep_statuses(ti, session, dep_context):
[2018-05-07 01:26:59,477] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-07 01:26:59,477] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/bin/airflow", line 28, in <module>
[2018-05-07 01:26:59,477] {base_task_runner.py:95} INFO - Subtask:     args.func(args)
[2018-05-07 01:26:59,477] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/bin/cli.py", line 422, in run
[2018-05-07 01:26:59,477] {base_task_runner.py:95} INFO - Subtask:     pool=args.pool,
[2018-05-07 01:26:59,477] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/utils/db.py", line 53, in wrapper
[2018-05-07 01:26:59,477] {base_task_runner.py:95} INFO - Subtask:     result = func(*args, **kwargs)
[2018-05-07 01:26:59,477] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/models.py", line 1374, in run
[2018-05-07 01:26:59,477] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-07 01:26:59,477] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-07 01:26:59,477] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-07 01:26:59,477] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/jobs/train_cv_test.py", line 194, in test_new
[2018-05-07 01:26:59,477] {base_task_runner.py:95} INFO - Subtask:     dump_stats=True)
[2018-05-07 01:26:59,477] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/src/conv_net/test.py", line 113, in run
[2018-05-07 01:26:59,477] {base_task_runner.py:95} INFO - Subtask:     checkpoint_paths = self.get_checkpoint_path(which_checkpoint)
[2018-05-07 01:26:59,478] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/src/conv_net/train.py", line 106, in get_checkpoint_path
[2018-05-07 01:26:59,478] {base_task_runner.py:95} INFO - Subtask:     checkpoints = [str(filename.split('.')[0]) for filename in os.listdir(self.ckpt_path)
[2018-05-07 01:26:59,478] {base_task_runner.py:95} INFO - Subtask: FileNotFoundError: [Errno 2] No such file or directory: '/Users/sam/All-Program/App-DataSet/HouseClassification/checkpoints/sam_new/overlaid/resnet'
[2018-05-07 01:27:00,387] {jobs.py:2083} INFO - Task exited with return code 1
[2018-05-07 01:30:01,328] {models.py:167} INFO - Filling up the DagBag from /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py
[2018-05-07 01:30:04,473] {base_task_runner.py:112} INFO - Running: ['bash', '-c', 'airflow run PropertyClassification_test_pipeline test_on_new_images 2018-05-07T01:23:50.810307 --job_id 186 --raw -sd /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py']
[2018-05-07 01:30:04,814] {base_task_runner.py:95} INFO - Subtask: [2018-05-07 01:30:04,814] {__init__.py:57} INFO - Using executor SequentialExecutor
[2018-05-07 01:30:05,234] {base_task_runner.py:95} INFO - Subtask: [2018-05-07 01:30:05,234] {models.py:167} INFO - Filling up the DagBag from /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py
[2018-05-07 01:30:08,358] {base_task_runner.py:95} INFO - Subtask: [2018-05-07 01:30:08,358] {models.py:1126} INFO - Dependencies all met for <TaskInstance: PropertyClassification_test_pipeline.test_on_new_images 2018-05-07 01:23:50.810307 [queued]>
[2018-05-07 01:30:08,364] {base_task_runner.py:95} INFO - Subtask: [2018-05-07 01:30:08,363] {models.py:1126} INFO - Dependencies all met for <TaskInstance: PropertyClassification_test_pipeline.test_on_new_images 2018-05-07 01:23:50.810307 [queued]>
[2018-05-07 01:30:08,364] {base_task_runner.py:95} INFO - Subtask: [2018-05-07 01:30:08,364] {models.py:1318} INFO - 
[2018-05-07 01:30:08,364] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-07 01:30:08,364] {base_task_runner.py:95} INFO - Subtask: Starting attempt 2 of 2
[2018-05-07 01:30:08,364] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-07 01:30:08,364] {base_task_runner.py:95} INFO - Subtask: 
[2018-05-07 01:30:08,373] {base_task_runner.py:95} INFO - Subtask: [2018-05-07 01:30:08,373] {models.py:1342} INFO - Executing <Task(PythonOperator): test_on_new_images> on 2018-05-07 01:23:50.810307
[2018-05-07 01:30:08,392] {base_task_runner.py:95} INFO - Subtask: [2018-05-07 01:30:08,391] {test.py:103} INFO - INITIATING TEST ........
[2018-05-07 01:30:08,393] {base_task_runner.py:95} INFO - Subtask: [2018-05-07 01:30:08,392] {models.py:1417} ERROR - [Errno 2] No such file or directory: '/Users/sam/All-Program/App-DataSet/HouseClassification/checkpoints/sam_new/overlaid/resnet'
[2018-05-07 01:30:08,393] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-07 01:30:08,393] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/models.py", line 1374, in run
[2018-05-07 01:30:08,393] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-07 01:30:08,393] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-07 01:30:08,393] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-07 01:30:08,393] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/jobs/train_cv_test.py", line 194, in test_new
[2018-05-07 01:30:08,393] {base_task_runner.py:95} INFO - Subtask:     dump_stats=True)
[2018-05-07 01:30:08,393] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/src/conv_net/test.py", line 113, in run
[2018-05-07 01:30:08,393] {base_task_runner.py:95} INFO - Subtask:     checkpoint_paths = self.get_checkpoint_path(which_checkpoint)
[2018-05-07 01:30:08,393] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/src/conv_net/train.py", line 106, in get_checkpoint_path
[2018-05-07 01:30:08,393] {base_task_runner.py:95} INFO - Subtask:     checkpoints = [str(filename.split('.')[0]) for filename in os.listdir(self.ckpt_path)
[2018-05-07 01:30:08,394] {base_task_runner.py:95} INFO - Subtask: FileNotFoundError: [Errno 2] No such file or directory: '/Users/sam/All-Program/App-DataSet/HouseClassification/checkpoints/sam_new/overlaid/resnet'
[2018-05-07 01:30:08,394] {base_task_runner.py:95} INFO - Subtask: [2018-05-07 01:30:08,394] {models.py:1439} INFO - All retries failed; marking task as FAILED
[2018-05-07 01:30:08,403] {base_task_runner.py:95} INFO - Subtask: [2018-05-07 01:30:08,403] {models.py:1462} ERROR - [Errno 2] No such file or directory: '/Users/sam/All-Program/App-DataSet/HouseClassification/checkpoints/sam_new/overlaid/resnet'
[2018-05-07 01:30:08,403] {base_task_runner.py:95} INFO - Subtask: /Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/ti_deps/deps/base_ti_dep.py:94: PendingDeprecationWarning: generator '_get_dep_statuses' raised StopIteration
[2018-05-07 01:30:08,403] {base_task_runner.py:95} INFO - Subtask:   for dep_status in self._get_dep_statuses(ti, session, dep_context):
[2018-05-07 01:30:08,405] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-07 01:30:08,405] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/bin/airflow", line 28, in <module>
[2018-05-07 01:30:08,405] {base_task_runner.py:95} INFO - Subtask:     args.func(args)
[2018-05-07 01:30:08,405] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/bin/cli.py", line 422, in run
[2018-05-07 01:30:08,405] {base_task_runner.py:95} INFO - Subtask:     pool=args.pool,
[2018-05-07 01:30:08,405] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/utils/db.py", line 53, in wrapper
[2018-05-07 01:30:08,405] {base_task_runner.py:95} INFO - Subtask:     result = func(*args, **kwargs)
[2018-05-07 01:30:08,405] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/models.py", line 1374, in run
[2018-05-07 01:30:08,405] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-07 01:30:08,405] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-07 01:30:08,405] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-07 01:30:08,405] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/jobs/train_cv_test.py", line 194, in test_new
[2018-05-07 01:30:08,405] {base_task_runner.py:95} INFO - Subtask:     dump_stats=True)
[2018-05-07 01:30:08,405] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/src/conv_net/test.py", line 113, in run
[2018-05-07 01:30:08,406] {base_task_runner.py:95} INFO - Subtask:     checkpoint_paths = self.get_checkpoint_path(which_checkpoint)
[2018-05-07 01:30:08,406] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/src/conv_net/train.py", line 106, in get_checkpoint_path
[2018-05-07 01:30:08,406] {base_task_runner.py:95} INFO - Subtask:     checkpoints = [str(filename.split('.')[0]) for filename in os.listdir(self.ckpt_path)
[2018-05-07 01:30:08,406] {base_task_runner.py:95} INFO - Subtask: FileNotFoundError: [Errno 2] No such file or directory: '/Users/sam/All-Program/App-DataSet/HouseClassification/checkpoints/sam_new/overlaid/resnet'
[2018-05-07 01:30:09,476] {jobs.py:2083} INFO - Task exited with return code 1
