[2018-05-04 10:54:45,215] {models.py:167} INFO - Filling up the DagBag from /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py
[2018-05-04 10:54:48,458] {base_task_runner.py:112} INFO - Running: ['bash', '-c', 'airflow run PropertyClassification_test_pipeline test_on_new_images 2018-05-03T00:00:00 --job_id 19 --raw -sd /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py']
[2018-05-04 10:54:48,829] {base_task_runner.py:95} INFO - Subtask: [2018-05-04 10:54:48,829] {__init__.py:57} INFO - Using executor SequentialExecutor
[2018-05-04 10:54:49,250] {base_task_runner.py:95} INFO - Subtask: [2018-05-04 10:54:49,250] {models.py:167} INFO - Filling up the DagBag from /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py
[2018-05-04 10:54:52,417] {base_task_runner.py:95} INFO - Subtask: [2018-05-04 10:54:52,417] {models.py:1126} INFO - Dependencies all met for <TaskInstance: PropertyClassification_test_pipeline.test_on_new_images 2018-05-03 00:00:00 [queued]>
[2018-05-04 10:54:52,423] {base_task_runner.py:95} INFO - Subtask: [2018-05-04 10:54:52,423] {models.py:1126} INFO - Dependencies all met for <TaskInstance: PropertyClassification_test_pipeline.test_on_new_images 2018-05-03 00:00:00 [queued]>
[2018-05-04 10:54:52,423] {base_task_runner.py:95} INFO - Subtask: [2018-05-04 10:54:52,423] {models.py:1318} INFO - 
[2018-05-04 10:54:52,424] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-04 10:54:52,424] {base_task_runner.py:95} INFO - Subtask: Starting attempt 1 of 2
[2018-05-04 10:54:52,424] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-04 10:54:52,424] {base_task_runner.py:95} INFO - Subtask: 
[2018-05-04 10:54:52,432] {base_task_runner.py:95} INFO - Subtask: [2018-05-04 10:54:52,432] {models.py:1342} INFO - Executing <Task(PythonOperator): test_on_new_images> on 2018-05-03 00:00:00
[2018-05-04 10:54:52,453] {base_task_runner.py:95} INFO - Subtask: [2018-05-04 10:54:52,452] {test.py:103} INFO - INITIATING TEST ........
[2018-05-04 10:54:52,454] {base_task_runner.py:95} INFO - Subtask: [2018-05-04 10:54:52,453] {models.py:1417} ERROR - [Errno 2] No such file or directory: '/Users/sam/All-Program/App-DataSet/HouseClassification/checkpoints/sam_new/aerial_cropped/resent'
[2018-05-04 10:54:52,454] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-04 10:54:52,454] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/models.py", line 1374, in run
[2018-05-04 10:54:52,454] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-04 10:54:52,454] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-04 10:54:52,455] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-04 10:54:52,455] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/jobs/train_cv_test.py", line 193, in test_new
[2018-05-04 10:54:52,455] {base_task_runner.py:95} INFO - Subtask:     dump_stats=True)
[2018-05-04 10:54:52,455] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/src/conv_net/test.py", line 113, in run
[2018-05-04 10:54:52,455] {base_task_runner.py:95} INFO - Subtask:     checkpoint_paths = self.get_checkpoint_path(which_checkpoint)
[2018-05-04 10:54:52,455] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/src/conv_net/train.py", line 106, in get_checkpoint_path
[2018-05-04 10:54:52,455] {base_task_runner.py:95} INFO - Subtask:     checkpoints = [str(filename.split('.')[0]) for filename in os.listdir(self.ckpt_path)
[2018-05-04 10:54:52,455] {base_task_runner.py:95} INFO - Subtask: FileNotFoundError: [Errno 2] No such file or directory: '/Users/sam/All-Program/App-DataSet/HouseClassification/checkpoints/sam_new/aerial_cropped/resent'
[2018-05-04 10:54:52,455] {base_task_runner.py:95} INFO - Subtask: [2018-05-04 10:54:52,455] {models.py:1433} INFO - Marking task as UP_FOR_RETRY
[2018-05-04 10:54:52,464] {base_task_runner.py:95} INFO - Subtask: [2018-05-04 10:54:52,464] {models.py:1462} ERROR - [Errno 2] No such file or directory: '/Users/sam/All-Program/App-DataSet/HouseClassification/checkpoints/sam_new/aerial_cropped/resent'
[2018-05-04 10:54:52,464] {base_task_runner.py:95} INFO - Subtask: /Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/ti_deps/deps/base_ti_dep.py:94: PendingDeprecationWarning: generator '_get_dep_statuses' raised StopIteration
[2018-05-04 10:54:52,464] {base_task_runner.py:95} INFO - Subtask:   for dep_status in self._get_dep_statuses(ti, session, dep_context):
[2018-05-04 10:54:52,465] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-04 10:54:52,465] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/bin/airflow", line 28, in <module>
[2018-05-04 10:54:52,466] {base_task_runner.py:95} INFO - Subtask:     args.func(args)
[2018-05-04 10:54:52,466] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/bin/cli.py", line 422, in run
[2018-05-04 10:54:52,466] {base_task_runner.py:95} INFO - Subtask:     pool=args.pool,
[2018-05-04 10:54:52,466] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/utils/db.py", line 53, in wrapper
[2018-05-04 10:54:52,466] {base_task_runner.py:95} INFO - Subtask:     result = func(*args, **kwargs)
[2018-05-04 10:54:52,466] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/models.py", line 1374, in run
[2018-05-04 10:54:52,466] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-04 10:54:52,466] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-04 10:54:52,466] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-04 10:54:52,466] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/jobs/train_cv_test.py", line 193, in test_new
[2018-05-04 10:54:52,466] {base_task_runner.py:95} INFO - Subtask:     dump_stats=True)
[2018-05-04 10:54:52,466] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/src/conv_net/test.py", line 113, in run
[2018-05-04 10:54:52,466] {base_task_runner.py:95} INFO - Subtask:     checkpoint_paths = self.get_checkpoint_path(which_checkpoint)
[2018-05-04 10:54:52,466] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/src/conv_net/train.py", line 106, in get_checkpoint_path
[2018-05-04 10:54:52,466] {base_task_runner.py:95} INFO - Subtask:     checkpoints = [str(filename.split('.')[0]) for filename in os.listdir(self.ckpt_path)
[2018-05-04 10:54:52,467] {base_task_runner.py:95} INFO - Subtask: FileNotFoundError: [Errno 2] No such file or directory: '/Users/sam/All-Program/App-DataSet/HouseClassification/checkpoints/sam_new/aerial_cropped/resent'
[2018-05-04 10:54:53,464] {jobs.py:2083} INFO - Task exited with return code 1
[2018-05-04 10:57:16,370] {models.py:167} INFO - Filling up the DagBag from /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py
[2018-05-04 10:57:19,635] {base_task_runner.py:112} INFO - Running: ['bash', '-c', 'airflow run PropertyClassification_test_pipeline test_on_new_images 2018-05-03T00:00:00 --job_id 23 --raw -sd /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py']
[2018-05-04 10:57:20,014] {base_task_runner.py:95} INFO - Subtask: [2018-05-04 10:57:20,014] {__init__.py:57} INFO - Using executor SequentialExecutor
[2018-05-04 10:57:20,437] {base_task_runner.py:95} INFO - Subtask: [2018-05-04 10:57:20,437] {models.py:167} INFO - Filling up the DagBag from /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py
[2018-05-04 10:57:23,747] {base_task_runner.py:95} INFO - Subtask: [2018-05-04 10:57:23,747] {models.py:1126} INFO - Dependencies all met for <TaskInstance: PropertyClassification_test_pipeline.test_on_new_images 2018-05-03 00:00:00 [queued]>
[2018-05-04 10:57:23,752] {base_task_runner.py:95} INFO - Subtask: [2018-05-04 10:57:23,752] {models.py:1126} INFO - Dependencies all met for <TaskInstance: PropertyClassification_test_pipeline.test_on_new_images 2018-05-03 00:00:00 [queued]>
[2018-05-04 10:57:23,752] {base_task_runner.py:95} INFO - Subtask: [2018-05-04 10:57:23,752] {models.py:1318} INFO - 
[2018-05-04 10:57:23,752] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-04 10:57:23,753] {base_task_runner.py:95} INFO - Subtask: Starting attempt 2 of 2
[2018-05-04 10:57:23,753] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-04 10:57:23,753] {base_task_runner.py:95} INFO - Subtask: 
[2018-05-04 10:57:23,761] {base_task_runner.py:95} INFO - Subtask: [2018-05-04 10:57:23,760] {models.py:1342} INFO - Executing <Task(PythonOperator): test_on_new_images> on 2018-05-03 00:00:00
[2018-05-04 10:57:23,779] {base_task_runner.py:95} INFO - Subtask: [2018-05-04 10:57:23,778] {test.py:103} INFO - INITIATING TEST ........
[2018-05-04 10:57:23,780] {base_task_runner.py:95} INFO - Subtask: [2018-05-04 10:57:23,779] {models.py:1417} ERROR - [Errno 2] No such file or directory: '/Users/sam/All-Program/App-DataSet/HouseClassification/checkpoints/sam_new/aerial_cropped/resent'
[2018-05-04 10:57:23,780] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-04 10:57:23,781] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/models.py", line 1374, in run
[2018-05-04 10:57:23,781] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-04 10:57:23,781] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-04 10:57:23,781] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-04 10:57:23,781] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/jobs/train_cv_test.py", line 193, in test_new
[2018-05-04 10:57:23,781] {base_task_runner.py:95} INFO - Subtask:     dump_stats=True)
[2018-05-04 10:57:23,781] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/src/conv_net/test.py", line 113, in run
[2018-05-04 10:57:23,781] {base_task_runner.py:95} INFO - Subtask:     checkpoint_paths = self.get_checkpoint_path(which_checkpoint)
[2018-05-04 10:57:23,781] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/src/conv_net/train.py", line 106, in get_checkpoint_path
[2018-05-04 10:57:23,781] {base_task_runner.py:95} INFO - Subtask:     checkpoints = [str(filename.split('.')[0]) for filename in os.listdir(self.ckpt_path)
[2018-05-04 10:57:23,781] {base_task_runner.py:95} INFO - Subtask: FileNotFoundError: [Errno 2] No such file or directory: '/Users/sam/All-Program/App-DataSet/HouseClassification/checkpoints/sam_new/aerial_cropped/resent'
[2018-05-04 10:57:23,781] {base_task_runner.py:95} INFO - Subtask: [2018-05-04 10:57:23,781] {models.py:1439} INFO - All retries failed; marking task as FAILED
[2018-05-04 10:57:23,792] {base_task_runner.py:95} INFO - Subtask: [2018-05-04 10:57:23,791] {models.py:1462} ERROR - [Errno 2] No such file or directory: '/Users/sam/All-Program/App-DataSet/HouseClassification/checkpoints/sam_new/aerial_cropped/resent'
[2018-05-04 10:57:23,792] {base_task_runner.py:95} INFO - Subtask: /Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/ti_deps/deps/base_ti_dep.py:94: PendingDeprecationWarning: generator '_get_dep_statuses' raised StopIteration
[2018-05-04 10:57:23,792] {base_task_runner.py:95} INFO - Subtask:   for dep_status in self._get_dep_statuses(ti, session, dep_context):
[2018-05-04 10:57:23,793] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-04 10:57:23,793] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/bin/airflow", line 28, in <module>
[2018-05-04 10:57:23,793] {base_task_runner.py:95} INFO - Subtask:     args.func(args)
[2018-05-04 10:57:23,793] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/bin/cli.py", line 422, in run
[2018-05-04 10:57:23,793] {base_task_runner.py:95} INFO - Subtask:     pool=args.pool,
[2018-05-04 10:57:23,793] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/utils/db.py", line 53, in wrapper
[2018-05-04 10:57:23,793] {base_task_runner.py:95} INFO - Subtask:     result = func(*args, **kwargs)
[2018-05-04 10:57:23,794] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/models.py", line 1374, in run
[2018-05-04 10:57:23,794] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-04 10:57:23,794] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-04 10:57:23,794] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-04 10:57:23,794] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/jobs/train_cv_test.py", line 193, in test_new
[2018-05-04 10:57:23,794] {base_task_runner.py:95} INFO - Subtask:     dump_stats=True)
[2018-05-04 10:57:23,794] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/src/conv_net/test.py", line 113, in run
[2018-05-04 10:57:23,794] {base_task_runner.py:95} INFO - Subtask:     checkpoint_paths = self.get_checkpoint_path(which_checkpoint)
[2018-05-04 10:57:23,794] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/src/conv_net/train.py", line 106, in get_checkpoint_path
[2018-05-04 10:57:23,794] {base_task_runner.py:95} INFO - Subtask:     checkpoints = [str(filename.split('.')[0]) for filename in os.listdir(self.ckpt_path)
[2018-05-04 10:57:23,794] {base_task_runner.py:95} INFO - Subtask: FileNotFoundError: [Errno 2] No such file or directory: '/Users/sam/All-Program/App-DataSet/HouseClassification/checkpoints/sam_new/aerial_cropped/resent'
[2018-05-04 10:57:24,638] {jobs.py:2083} INFO - Task exited with return code 1
