[2018-05-06 20:22:10,500] {models.py:167} INFO - Filling up the DagBag from /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py
[2018-05-06 20:22:13,521] {base_task_runner.py:112} INFO - Running: ['bash', '-c', 'airflow run PropertyClassification_test_pipeline clean_filter_records 2018-05-06T19:19:00.939526 --job_id 134 --raw -sd /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py']
[2018-05-06 20:22:13,843] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:22:13,843] {__init__.py:57} INFO - Using executor SequentialExecutor
[2018-05-06 20:22:14,256] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:22:14,256] {models.py:167} INFO - Filling up the DagBag from /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py
[2018-05-06 20:22:17,521] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:22:17,521] {models.py:1126} INFO - Dependencies all met for <TaskInstance: PropertyClassification_test_pipeline.clean_filter_records 2018-05-06 19:19:00.939526 [queued]>
[2018-05-06 20:22:17,524] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:22:17,524] {models.py:1126} INFO - Dependencies all met for <TaskInstance: PropertyClassification_test_pipeline.clean_filter_records 2018-05-06 19:19:00.939526 [queued]>
[2018-05-06 20:22:17,524] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:22:17,524] {models.py:1318} INFO - 
[2018-05-06 20:22:17,524] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-06 20:22:17,524] {base_task_runner.py:95} INFO - Subtask: Starting attempt 1 of 2
[2018-05-06 20:22:17,524] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-06 20:22:17,524] {base_task_runner.py:95} INFO - Subtask: 
[2018-05-06 20:22:17,533] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:22:17,533] {models.py:1342} INFO - Executing <Task(PythonOperator): clean_filter_records> on 2018-05-06 19:19:00.939526
[2018-05-06 20:22:19,733] {base_task_runner.py:95} INFO - Subtask: Shape: Metadata table (220364, 18)
[2018-05-06 20:22:19,733] {base_task_runner.py:95} INFO - Subtask: Data shape  = (220364, 18)
[2018-05-06 20:22:19,733] {base_task_runner.py:95} INFO - Subtask: Applying conditions: from_year 2015 - to_year 2015
[2018-05-06 20:22:19,734] {base_task_runner.py:95} INFO - Subtask: Data shape  = (21683, 18)
[2018-05-06 20:22:19,734] {base_task_runner.py:95} INFO - Subtask: Applying conditions: from_month 6 - to_month 6
[2018-05-06 20:22:19,734] {base_task_runner.py:95} INFO - Subtask: Data shape  = (11175, 18)
[2018-05-06 20:22:19,734] {base_task_runner.py:95} INFO - Subtask: Applying conditions: city: chicago
[2018-05-06 20:22:19,734] {base_task_runner.py:95} INFO - Subtask: Data shape  = (9267, 18)
[2018-05-06 20:22:19,734] {base_task_runner.py:95} INFO - Subtask: Applying conditions: improvement_lvl: True
[2018-05-06 20:22:19,734] {base_task_runner.py:95} INFO - Subtask: Data shape land = (4265, 18), house = (4897, 18)
[2018-05-06 20:22:19,734] {base_task_runner.py:95} INFO - Subtask: Applying conditions: max_num_records: 264
[2018-05-06 20:22:19,734] {base_task_runner.py:95} INFO - Subtask: Shape: Land Property table (132, 18)
[2018-05-06 20:22:19,734] {base_task_runner.py:95} INFO - Subtask: Shape: House Property table (132, 18)
[2018-05-06 20:22:19,734] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:22:19,726] {models.py:1417} ERROR - [Errno 2] No such file or directory: '/Users/sam/All-Program/App-DataSet/HouseClassification/input_csv_files/PreTestRun/aerial_cropped/input_data.csv'
[2018-05-06 20:22:19,734] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-06 20:22:19,734] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/models.py", line 1374, in run
[2018-05-06 20:22:19,734] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-06 20:22:19,735] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-06 20:22:19,735] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-06 20:22:19,735] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/jobs/data_load.py", line 302, in create_csv_file_for_input
[2018-05-06 20:22:19,735] {base_task_runner.py:95} INFO - Subtask:     status = data_selection_cond(conf, inp_params['cond_dict'], inp_params['input_csv_path'])
[2018-05-06 20:22:19,735] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/jobs/data_load.py", line 269, in data_selection_cond
[2018-05-06 20:22:19,735] {base_task_runner.py:95} INFO - Subtask:     filtered_data.to_csv(os.path.join(conf['pathDict']['csv_path'], 'input_data.csv'), index=None)
[2018-05-06 20:22:19,735] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/pandas/core/frame.py", line 1403, in to_csv
[2018-05-06 20:22:19,735] {base_task_runner.py:95} INFO - Subtask:     formatter.save()
[2018-05-06 20:22:19,735] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/pandas/io/formats/format.py", line 1577, in save
[2018-05-06 20:22:19,735] {base_task_runner.py:95} INFO - Subtask:     compression=self.compression)
[2018-05-06 20:22:19,735] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/pandas/io/common.py", line 385, in _get_handle
[2018-05-06 20:22:19,735] {base_task_runner.py:95} INFO - Subtask:     f = open(path_or_buf, mode, errors='replace')
[2018-05-06 20:22:19,735] {base_task_runner.py:95} INFO - Subtask: FileNotFoundError: [Errno 2] No such file or directory: '/Users/sam/All-Program/App-DataSet/HouseClassification/input_csv_files/PreTestRun/aerial_cropped/input_data.csv'
[2018-05-06 20:22:19,735] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:22:19,734] {models.py:1433} INFO - Marking task as UP_FOR_RETRY
[2018-05-06 20:22:19,745] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:22:19,745] {models.py:1462} ERROR - [Errno 2] No such file or directory: '/Users/sam/All-Program/App-DataSet/HouseClassification/input_csv_files/PreTestRun/aerial_cropped/input_data.csv'
[2018-05-06 20:22:19,745] {base_task_runner.py:95} INFO - Subtask: /Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/ti_deps/deps/base_ti_dep.py:94: PendingDeprecationWarning: generator '_get_dep_statuses' raised StopIteration
[2018-05-06 20:22:19,745] {base_task_runner.py:95} INFO - Subtask:   for dep_status in self._get_dep_statuses(ti, session, dep_context):
[2018-05-06 20:22:19,745] {base_task_runner.py:95} INFO - Subtask: /Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/models.py:1374: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
[2018-05-06 20:22:19,745] {base_task_runner.py:95} INFO - Subtask:   result = task_copy.execute(context=context)
[2018-05-06 20:22:19,747] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-06 20:22:19,747] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/bin/airflow", line 28, in <module>
[2018-05-06 20:22:19,747] {base_task_runner.py:95} INFO - Subtask:     args.func(args)
[2018-05-06 20:22:19,747] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/bin/cli.py", line 422, in run
[2018-05-06 20:22:19,748] {base_task_runner.py:95} INFO - Subtask:     pool=args.pool,
[2018-05-06 20:22:19,748] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/utils/db.py", line 53, in wrapper
[2018-05-06 20:22:19,748] {base_task_runner.py:95} INFO - Subtask:     result = func(*args, **kwargs)
[2018-05-06 20:22:19,748] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/models.py", line 1374, in run
[2018-05-06 20:22:19,748] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-06 20:22:19,748] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-06 20:22:19,748] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-06 20:22:19,748] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/jobs/data_load.py", line 302, in create_csv_file_for_input
[2018-05-06 20:22:19,748] {base_task_runner.py:95} INFO - Subtask:     status = data_selection_cond(conf, inp_params['cond_dict'], inp_params['input_csv_path'])
[2018-05-06 20:22:19,748] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/jobs/data_load.py", line 269, in data_selection_cond
[2018-05-06 20:22:19,748] {base_task_runner.py:95} INFO - Subtask:     filtered_data.to_csv(os.path.join(conf['pathDict']['csv_path'], 'input_data.csv'), index=None)
[2018-05-06 20:22:19,748] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/pandas/core/frame.py", line 1403, in to_csv
[2018-05-06 20:22:19,748] {base_task_runner.py:95} INFO - Subtask:     formatter.save()
[2018-05-06 20:22:19,748] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/pandas/io/formats/format.py", line 1577, in save
[2018-05-06 20:22:19,748] {base_task_runner.py:95} INFO - Subtask:     compression=self.compression)
[2018-05-06 20:22:19,748] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/pandas/io/common.py", line 385, in _get_handle
[2018-05-06 20:22:19,748] {base_task_runner.py:95} INFO - Subtask:     f = open(path_or_buf, mode, errors='replace')
[2018-05-06 20:22:19,749] {base_task_runner.py:95} INFO - Subtask: FileNotFoundError: [Errno 2] No such file or directory: '/Users/sam/All-Program/App-DataSet/HouseClassification/input_csv_files/PreTestRun/aerial_cropped/input_data.csv'
[2018-05-06 20:22:23,527] {jobs.py:2083} INFO - Task exited with return code 1
[2018-05-06 20:24:25,939] {models.py:167} INFO - Filling up the DagBag from /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py
[2018-05-06 20:24:29,027] {base_task_runner.py:112} INFO - Running: ['bash', '-c', 'airflow run PropertyClassification_test_pipeline clean_filter_records 2018-05-06T19:19:00.939526 --job_id 137 --raw -sd /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py']
[2018-05-06 20:24:29,391] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:24:29,390] {__init__.py:57} INFO - Using executor SequentialExecutor
[2018-05-06 20:24:29,790] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:24:29,790] {models.py:167} INFO - Filling up the DagBag from /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py
[2018-05-06 20:24:32,833] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:24:32,832] {models.py:1126} INFO - Dependencies all met for <TaskInstance: PropertyClassification_test_pipeline.clean_filter_records 2018-05-06 19:19:00.939526 [queued]>
[2018-05-06 20:24:32,835] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:24:32,835] {models.py:1126} INFO - Dependencies all met for <TaskInstance: PropertyClassification_test_pipeline.clean_filter_records 2018-05-06 19:19:00.939526 [queued]>
[2018-05-06 20:24:32,835] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:24:32,835] {models.py:1318} INFO - 
[2018-05-06 20:24:32,835] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-06 20:24:32,835] {base_task_runner.py:95} INFO - Subtask: Starting attempt 2 of 2
[2018-05-06 20:24:32,835] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-06 20:24:32,836] {base_task_runner.py:95} INFO - Subtask: 
[2018-05-06 20:24:32,844] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:24:32,844] {models.py:1342} INFO - Executing <Task(PythonOperator): clean_filter_records> on 2018-05-06 19:19:00.939526
[2018-05-06 20:24:35,038] {base_task_runner.py:95} INFO - Subtask: Shape: Metadata table (220364, 18)
[2018-05-06 20:24:35,038] {base_task_runner.py:95} INFO - Subtask: Data shape  = (220364, 18)
[2018-05-06 20:24:35,038] {base_task_runner.py:95} INFO - Subtask: Applying conditions: from_year 2015 - to_year 2015
[2018-05-06 20:24:35,038] {base_task_runner.py:95} INFO - Subtask: Data shape  = (21683, 18)
[2018-05-06 20:24:35,038] {base_task_runner.py:95} INFO - Subtask: Applying conditions: from_month 6 - to_month 6
[2018-05-06 20:24:35,038] {base_task_runner.py:95} INFO - Subtask: Data shape  = (11175, 18)
[2018-05-06 20:24:35,038] {base_task_runner.py:95} INFO - Subtask: Applying conditions: city: chicago
[2018-05-06 20:24:35,038] {base_task_runner.py:95} INFO - Subtask: Data shape  = (9267, 18)
[2018-05-06 20:24:35,038] {base_task_runner.py:95} INFO - Subtask: Applying conditions: improvement_lvl: True
[2018-05-06 20:24:35,039] {base_task_runner.py:95} INFO - Subtask: Data shape land = (4265, 18), house = (4897, 18)
[2018-05-06 20:24:35,039] {base_task_runner.py:95} INFO - Subtask: Applying conditions: max_num_records: 264
[2018-05-06 20:24:35,039] {base_task_runner.py:95} INFO - Subtask: Shape: Land Property table (132, 18)
[2018-05-06 20:24:35,039] {base_task_runner.py:95} INFO - Subtask: Shape: House Property table (132, 18)
[2018-05-06 20:24:35,039] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:24:35,035] {models.py:1417} ERROR - [Errno 2] No such file or directory: '/Users/sam/All-Program/App-DataSet/HouseClassification/input_csv_files/PreTestRun/aerial_cropped/input_data.csv'
[2018-05-06 20:24:35,039] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-06 20:24:35,039] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/models.py", line 1374, in run
[2018-05-06 20:24:35,039] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-06 20:24:35,039] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-06 20:24:35,039] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-06 20:24:35,039] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/jobs/data_load.py", line 300, in create_csv_file_for_input
[2018-05-06 20:24:35,039] {base_task_runner.py:95} INFO - Subtask:     status = data_selection_cond(conf, inp_params['cond_dict'], inp_params['input_csv_path'])
[2018-05-06 20:24:35,039] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/jobs/data_load.py", line 267, in data_selection_cond
[2018-05-06 20:24:35,039] {base_task_runner.py:95} INFO - Subtask:     filtered_data.to_csv(os.path.join(conf['pathDict']['csv_path'], 'input_data.csv'), index=None)
[2018-05-06 20:24:35,039] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/pandas/core/frame.py", line 1403, in to_csv
[2018-05-06 20:24:35,039] {base_task_runner.py:95} INFO - Subtask:     formatter.save()
[2018-05-06 20:24:35,040] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/pandas/io/formats/format.py", line 1577, in save
[2018-05-06 20:24:35,040] {base_task_runner.py:95} INFO - Subtask:     compression=self.compression)
[2018-05-06 20:24:35,040] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/pandas/io/common.py", line 385, in _get_handle
[2018-05-06 20:24:35,040] {base_task_runner.py:95} INFO - Subtask:     f = open(path_or_buf, mode, errors='replace')
[2018-05-06 20:24:35,040] {base_task_runner.py:95} INFO - Subtask: FileNotFoundError: [Errno 2] No such file or directory: '/Users/sam/All-Program/App-DataSet/HouseClassification/input_csv_files/PreTestRun/aerial_cropped/input_data.csv'
[2018-05-06 20:24:35,040] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:24:35,039] {models.py:1439} INFO - All retries failed; marking task as FAILED
[2018-05-06 20:24:35,050] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:24:35,049] {models.py:1462} ERROR - [Errno 2] No such file or directory: '/Users/sam/All-Program/App-DataSet/HouseClassification/input_csv_files/PreTestRun/aerial_cropped/input_data.csv'
[2018-05-06 20:24:35,050] {base_task_runner.py:95} INFO - Subtask: /Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/ti_deps/deps/base_ti_dep.py:94: PendingDeprecationWarning: generator '_get_dep_statuses' raised StopIteration
[2018-05-06 20:24:35,050] {base_task_runner.py:95} INFO - Subtask:   for dep_status in self._get_dep_statuses(ti, session, dep_context):
[2018-05-06 20:24:35,050] {base_task_runner.py:95} INFO - Subtask: /Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/models.py:1374: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
[2018-05-06 20:24:35,050] {base_task_runner.py:95} INFO - Subtask:   result = task_copy.execute(context=context)
[2018-05-06 20:24:35,052] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-06 20:24:35,052] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/bin/airflow", line 28, in <module>
[2018-05-06 20:24:35,052] {base_task_runner.py:95} INFO - Subtask:     args.func(args)
[2018-05-06 20:24:35,052] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/bin/cli.py", line 422, in run
[2018-05-06 20:24:35,052] {base_task_runner.py:95} INFO - Subtask:     pool=args.pool,
[2018-05-06 20:24:35,052] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/utils/db.py", line 53, in wrapper
[2018-05-06 20:24:35,052] {base_task_runner.py:95} INFO - Subtask:     result = func(*args, **kwargs)
[2018-05-06 20:24:35,053] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/models.py", line 1374, in run
[2018-05-06 20:24:35,053] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-06 20:24:35,053] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-06 20:24:35,053] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-06 20:24:35,053] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/jobs/data_load.py", line 300, in create_csv_file_for_input
[2018-05-06 20:24:35,053] {base_task_runner.py:95} INFO - Subtask:     status = data_selection_cond(conf, inp_params['cond_dict'], inp_params['input_csv_path'])
[2018-05-06 20:24:35,053] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/jobs/data_load.py", line 267, in data_selection_cond
[2018-05-06 20:24:35,053] {base_task_runner.py:95} INFO - Subtask:     filtered_data.to_csv(os.path.join(conf['pathDict']['csv_path'], 'input_data.csv'), index=None)
[2018-05-06 20:24:35,053] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/pandas/core/frame.py", line 1403, in to_csv
[2018-05-06 20:24:35,053] {base_task_runner.py:95} INFO - Subtask:     formatter.save()
[2018-05-06 20:24:35,053] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/pandas/io/formats/format.py", line 1577, in save
[2018-05-06 20:24:35,053] {base_task_runner.py:95} INFO - Subtask:     compression=self.compression)
[2018-05-06 20:24:35,053] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/pandas/io/common.py", line 385, in _get_handle
[2018-05-06 20:24:35,053] {base_task_runner.py:95} INFO - Subtask:     f = open(path_or_buf, mode, errors='replace')
[2018-05-06 20:24:35,053] {base_task_runner.py:95} INFO - Subtask: FileNotFoundError: [Errno 2] No such file or directory: '/Users/sam/All-Program/App-DataSet/HouseClassification/input_csv_files/PreTestRun/aerial_cropped/input_data.csv'
[2018-05-06 20:24:39,040] {jobs.py:2083} INFO - Task exited with return code 1
