[2018-05-06 20:24:40,192] {models.py:167} INFO - Filling up the DagBag from /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py
[2018-05-06 20:24:43,366] {base_task_runner.py:112} INFO - Running: ['bash', '-c', 'airflow run PropertyClassification_test_pipeline clean_filter_records 2018-05-06T20:24:14.504986 --job_id 138 --raw -sd /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py']
[2018-05-06 20:24:43,747] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:24:43,747] {__init__.py:57} INFO - Using executor SequentialExecutor
[2018-05-06 20:24:44,165] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:24:44,165] {models.py:167} INFO - Filling up the DagBag from /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py
[2018-05-06 20:24:47,467] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:24:47,466] {models.py:1126} INFO - Dependencies all met for <TaskInstance: PropertyClassification_test_pipeline.clean_filter_records 2018-05-06 20:24:14.504986 [queued]>
[2018-05-06 20:24:47,468] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:24:47,468] {models.py:1126} INFO - Dependencies all met for <TaskInstance: PropertyClassification_test_pipeline.clean_filter_records 2018-05-06 20:24:14.504986 [queued]>
[2018-05-06 20:24:47,469] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:24:47,468] {models.py:1318} INFO - 
[2018-05-06 20:24:47,469] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-06 20:24:47,469] {base_task_runner.py:95} INFO - Subtask: Starting attempt 1 of 2
[2018-05-06 20:24:47,469] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-06 20:24:47,469] {base_task_runner.py:95} INFO - Subtask: 
[2018-05-06 20:24:47,476] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:24:47,475] {models.py:1342} INFO - Executing <Task(PythonOperator): clean_filter_records> on 2018-05-06 20:24:14.504986
[2018-05-06 20:24:49,782] {base_task_runner.py:95} INFO - Subtask: Shape: Metadata table (220364, 18)
[2018-05-06 20:24:49,782] {base_task_runner.py:95} INFO - Subtask: Data shape  = (220364, 18)
[2018-05-06 20:24:49,782] {base_task_runner.py:95} INFO - Subtask: Applying conditions: from_year 2015 - to_year 2015
[2018-05-06 20:24:49,782] {base_task_runner.py:95} INFO - Subtask: Data shape  = (21683, 18)
[2018-05-06 20:24:49,782] {base_task_runner.py:95} INFO - Subtask: Applying conditions: from_month 6 - to_month 6
[2018-05-06 20:24:49,783] {base_task_runner.py:95} INFO - Subtask: Data shape  = (11175, 18)
[2018-05-06 20:24:49,783] {base_task_runner.py:95} INFO - Subtask: Applying conditions: city: chicago
[2018-05-06 20:24:49,783] {base_task_runner.py:95} INFO - Subtask: Data shape  = (9267, 18)
[2018-05-06 20:24:49,783] {base_task_runner.py:95} INFO - Subtask: Applying conditions: improvement_lvl: True
[2018-05-06 20:24:49,783] {base_task_runner.py:95} INFO - Subtask: Data shape land = (4265, 18), house = (4897, 18)
[2018-05-06 20:24:49,783] {base_task_runner.py:95} INFO - Subtask: Applying conditions: max_num_records: 264
[2018-05-06 20:24:49,783] {base_task_runner.py:95} INFO - Subtask: Shape: Land Property table (132, 18)
[2018-05-06 20:24:49,783] {base_task_runner.py:95} INFO - Subtask: Shape: House Property table (132, 18)
[2018-05-06 20:24:49,783] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:24:49,780] {models.py:1417} ERROR - [Errno 2] No such file or directory: '/Users/sam/All-Program/App-DataSet/HouseClassification/input_csv_files/PreTestRun/aerial_cropped/input_data.csv'
[2018-05-06 20:24:49,783] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-06 20:24:49,783] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/models.py", line 1374, in run
[2018-05-06 20:24:49,783] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-06 20:24:49,783] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-06 20:24:49,783] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-06 20:24:49,783] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/jobs/data_load.py", line 300, in create_csv_file_for_input
[2018-05-06 20:24:49,783] {base_task_runner.py:95} INFO - Subtask:     status = data_selection_cond(conf, inp_params['cond_dict'], inp_params['input_csv_path'])
[2018-05-06 20:24:49,784] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/jobs/data_load.py", line 267, in data_selection_cond
[2018-05-06 20:24:49,784] {base_task_runner.py:95} INFO - Subtask:     filtered_data.to_csv(os.path.join(conf['pathDict']['csv_path'], 'input_data.csv'), index=None)
[2018-05-06 20:24:49,784] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/pandas/core/frame.py", line 1403, in to_csv
[2018-05-06 20:24:49,784] {base_task_runner.py:95} INFO - Subtask:     formatter.save()
[2018-05-06 20:24:49,784] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/pandas/io/formats/format.py", line 1577, in save
[2018-05-06 20:24:49,784] {base_task_runner.py:95} INFO - Subtask:     compression=self.compression)
[2018-05-06 20:24:49,784] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/pandas/io/common.py", line 385, in _get_handle
[2018-05-06 20:24:49,784] {base_task_runner.py:95} INFO - Subtask:     f = open(path_or_buf, mode, errors='replace')
[2018-05-06 20:24:49,784] {base_task_runner.py:95} INFO - Subtask: FileNotFoundError: [Errno 2] No such file or directory: '/Users/sam/All-Program/App-DataSet/HouseClassification/input_csv_files/PreTestRun/aerial_cropped/input_data.csv'
[2018-05-06 20:24:49,784] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:24:49,783] {models.py:1433} INFO - Marking task as UP_FOR_RETRY
[2018-05-06 20:24:49,796] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:24:49,795] {models.py:1462} ERROR - [Errno 2] No such file or directory: '/Users/sam/All-Program/App-DataSet/HouseClassification/input_csv_files/PreTestRun/aerial_cropped/input_data.csv'
[2018-05-06 20:24:49,796] {base_task_runner.py:95} INFO - Subtask: /Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/ti_deps/deps/base_ti_dep.py:94: PendingDeprecationWarning: generator '_get_dep_statuses' raised StopIteration
[2018-05-06 20:24:49,796] {base_task_runner.py:95} INFO - Subtask:   for dep_status in self._get_dep_statuses(ti, session, dep_context):
[2018-05-06 20:24:49,796] {base_task_runner.py:95} INFO - Subtask: /Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/models.py:1374: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
[2018-05-06 20:24:49,796] {base_task_runner.py:95} INFO - Subtask:   result = task_copy.execute(context=context)
[2018-05-06 20:24:49,798] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-06 20:24:49,799] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/bin/airflow", line 28, in <module>
[2018-05-06 20:24:49,799] {base_task_runner.py:95} INFO - Subtask:     args.func(args)
[2018-05-06 20:24:49,799] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/bin/cli.py", line 422, in run
[2018-05-06 20:24:49,799] {base_task_runner.py:95} INFO - Subtask:     pool=args.pool,
[2018-05-06 20:24:49,799] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/utils/db.py", line 53, in wrapper
[2018-05-06 20:24:49,799] {base_task_runner.py:95} INFO - Subtask:     result = func(*args, **kwargs)
[2018-05-06 20:24:49,799] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/models.py", line 1374, in run
[2018-05-06 20:24:49,799] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-06 20:24:49,799] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-06 20:24:49,799] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-06 20:24:49,799] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/jobs/data_load.py", line 300, in create_csv_file_for_input
[2018-05-06 20:24:49,799] {base_task_runner.py:95} INFO - Subtask:     status = data_selection_cond(conf, inp_params['cond_dict'], inp_params['input_csv_path'])
[2018-05-06 20:24:49,799] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/All-Program/App/PropertyClassification/jobs/data_load.py", line 267, in data_selection_cond
[2018-05-06 20:24:49,799] {base_task_runner.py:95} INFO - Subtask:     filtered_data.to_csv(os.path.join(conf['pathDict']['csv_path'], 'input_data.csv'), index=None)
[2018-05-06 20:24:49,799] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/pandas/core/frame.py", line 1403, in to_csv
[2018-05-06 20:24:49,799] {base_task_runner.py:95} INFO - Subtask:     formatter.save()
[2018-05-06 20:24:49,799] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/pandas/io/formats/format.py", line 1577, in save
[2018-05-06 20:24:49,800] {base_task_runner.py:95} INFO - Subtask:     compression=self.compression)
[2018-05-06 20:24:49,800] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/pandas/io/common.py", line 385, in _get_handle
[2018-05-06 20:24:49,800] {base_task_runner.py:95} INFO - Subtask:     f = open(path_or_buf, mode, errors='replace')
[2018-05-06 20:24:49,800] {base_task_runner.py:95} INFO - Subtask: FileNotFoundError: [Errno 2] No such file or directory: '/Users/sam/All-Program/App-DataSet/HouseClassification/input_csv_files/PreTestRun/aerial_cropped/input_data.csv'
[2018-05-06 20:24:53,375] {jobs.py:2083} INFO - Task exited with return code 1
[2018-05-06 20:27:30,092] {models.py:167} INFO - Filling up the DagBag from /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py
[2018-05-06 20:27:33,140] {base_task_runner.py:112} INFO - Running: ['bash', '-c', 'airflow run PropertyClassification_test_pipeline clean_filter_records 2018-05-06T20:24:14.504986 --job_id 142 --raw -sd /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py']
[2018-05-06 20:27:33,473] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:27:33,473] {__init__.py:57} INFO - Using executor SequentialExecutor
[2018-05-06 20:27:33,876] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:27:33,875] {models.py:167} INFO - Filling up the DagBag from /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py
[2018-05-06 20:27:36,899] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:27:36,898] {models.py:1126} INFO - Dependencies all met for <TaskInstance: PropertyClassification_test_pipeline.clean_filter_records 2018-05-06 20:24:14.504986 [queued]>
[2018-05-06 20:27:36,901] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:27:36,901] {models.py:1126} INFO - Dependencies all met for <TaskInstance: PropertyClassification_test_pipeline.clean_filter_records 2018-05-06 20:24:14.504986 [queued]>
[2018-05-06 20:27:36,901] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:27:36,901] {models.py:1318} INFO - 
[2018-05-06 20:27:36,901] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-06 20:27:36,901] {base_task_runner.py:95} INFO - Subtask: Starting attempt 2 of 2
[2018-05-06 20:27:36,901] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-06 20:27:36,901] {base_task_runner.py:95} INFO - Subtask: 
[2018-05-06 20:27:36,910] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:27:36,910] {models.py:1342} INFO - Executing <Task(PythonOperator): clean_filter_records> on 2018-05-06 20:24:14.504986
[2018-05-06 20:27:39,105] {base_task_runner.py:95} INFO - Subtask: Shape: Metadata table (220364, 18)
[2018-05-06 20:27:39,105] {base_task_runner.py:95} INFO - Subtask: Data shape  = (220364, 18)
[2018-05-06 20:27:39,105] {base_task_runner.py:95} INFO - Subtask: Applying conditions: from_year 2015 - to_year 2015
[2018-05-06 20:27:39,105] {base_task_runner.py:95} INFO - Subtask: Data shape  = (21683, 18)
[2018-05-06 20:27:39,105] {base_task_runner.py:95} INFO - Subtask: Applying conditions: from_month 6 - to_month 6
[2018-05-06 20:27:39,105] {base_task_runner.py:95} INFO - Subtask: Data shape  = (11175, 18)
[2018-05-06 20:27:39,105] {base_task_runner.py:95} INFO - Subtask: Applying conditions: city: chicago
[2018-05-06 20:27:39,105] {base_task_runner.py:95} INFO - Subtask: Data shape  = (9267, 18)
[2018-05-06 20:27:39,105] {base_task_runner.py:95} INFO - Subtask: Applying conditions: improvement_lvl: True
[2018-05-06 20:27:39,105] {base_task_runner.py:95} INFO - Subtask: Data shape land = (4265, 18), house = (4897, 18)
[2018-05-06 20:27:39,105] {base_task_runner.py:95} INFO - Subtask: Applying conditions: max_num_records: 264
[2018-05-06 20:27:39,105] {base_task_runner.py:95} INFO - Subtask: Shape: Land Property table (132, 18)
[2018-05-06 20:27:39,105] {base_task_runner.py:95} INFO - Subtask: Shape: House Property table (132, 18)
[2018-05-06 20:27:39,105] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 20:27:39,104] {python_operator.py:81} INFO - Done. Returned value was: COMPLETE
[2018-05-06 20:27:39,130] {base_task_runner.py:95} INFO - Subtask: /Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/ti_deps/deps/base_ti_dep.py:94: PendingDeprecationWarning: generator '_get_dep_statuses' raised StopIteration
[2018-05-06 20:27:39,131] {base_task_runner.py:95} INFO - Subtask:   for dep_status in self._get_dep_statuses(ti, session, dep_context):
[2018-05-06 20:27:39,131] {base_task_runner.py:95} INFO - Subtask: /Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/models.py:1374: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
[2018-05-06 20:27:39,131] {base_task_runner.py:95} INFO - Subtask:   result = task_copy.execute(context=context)
[2018-05-06 20:27:43,156] {jobs.py:2083} INFO - Task exited with return code 0
